### ISSUE TITLE
Meta: Documentation

### ISSUE THREAD

**Issue by robere2** [rpitv/glimpse-api#68]
Documentation is lackluster for this repository. I have been working on improving it within the repository's wiki. ~A set of goals needs to be outlined for what we want documented in order for this issue to be considered "complete"~

- [x] Introduction/NestJS
- [x] Authentication flow (Passport.js)
- [x] Authorization flow (@Rule)
- [x] Query complexities
- [x] CASL integration
- [x] Prisma integration/migrations
- [x] Prisma types
- [x] `StreamModule`
- [x] Glossary
- [x] GraphQL Input types
- [x] Database bootstrapping
- [x] Deployment/Docker

https://github.com/rpitv/glimpse-api/wiki

This is carried over from #53

**Comment by robere2** [comment]
Check list complete. Need to do a final review later tonight, then this issue will be complete. Please feel free to review now and share if you have any feedback.
